export const routes = {
  global: {
    initialScreen: 'initial-screen',
  },
  public: {
    loginOrRegisterIntroScreen: 'login-or-register-intro-screen',
    loginScreen: 'login-screen',
    registerScreen: 'register-screen',
    signupOtpScreen: 'signup-otp-screen',
    forgotPasswordScreen: 'forgot-password-screen',
    resetPasswordOtpScreen: 'reset-password-otp-screen',
    resetPasswordScreen: 'reset-password-screen',
    resetPasswordSuccessScreen: 'reset-password-success-screen',
    pricingListScreen: 'pricing-list-screen',
    termsAndConditionsScreen: 'public-terms-and-conditions-screen',
  },

  private: {
    dashboardScreen: 'dashboard-screen',
    notificationsScreen: 'notifications-screen',
    profileSettingsScreen: 'profile-settings-screen',
    editProfileScreen: 'edit-profile-screen',
    pricingScreen: 'pricing-screen',
    packagePurchaseScreen: 'package-purchase-screen',
    packagePurchaseSuccessScreen: 'package-purchase-success-screen',
    referredUsersScreen: 'referred-users-screen',
    transactionsScreen: 'transactions-screen',
    supportMessagesScreen: 'support-messages-screen',
    tasksScreen: 'tasks-screen',
    adPreviewScreen: 'ad-preview-screen',
    withdrawalRequestScreen: 'withdrawal-request-screen',
    globalNoticesScreen: 'global-notices-screen',
    globalNoticeDetailsScreen: 'global-notice-details-screen',
    paymentMethodEditScreen: 'payment-method-edit-screen',
    tutorialVideosScreen: 'tutorial-videos-screen',
    tutorialVideoPreviewScreen: 'tutorial-video-preview-screen',
    termsAndConditionsScreen: 'private-terms-and-conditions-screen',
    aboutUsScreen: 'about-us-screen',
  },
};
